# Generated by Django 6.0.8 on 2026-08-13 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuthSessionModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='auth_app.usermodel')),
            ],
            options={
                'db_table': 'auth_sessions',
                'indexes': [models.Index(fields=['user'], name='idx_auth_sessions_user_id'), models.Index(fields=['revoked_at'], name='idx_auth_sessions_revoked_at')],
            },
        ),
    ]
