# Generated by Django 6.0.8 on 2026-08-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="authsessionmodel",
            name="idx_auth_sessions_user_id",
        ),
        migrations.RemoveIndex(
            model_name="authsessionmodel",
            name="idx_auth_sessions_revoked_at",
        ),
    ]
