# Generated by Django 6.0.8 on 2026-08-13 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategoryModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_user', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='auth_app.usermodel')),
            ],
            options={
                'db_table': 'task_categories',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, db_column='task_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategorymodel')),
                ('owner_user', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to='auth_app.usermodel')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskShareModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('reader', 'Leitor')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_with_user', models.ForeignKey(db_column='shared_with_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_task_shares', to='auth_app.usermodel')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tasks.taskmodel')),
            ],
            options={
                'db_table': 'task_shares',
            },
        ),
        migrations.AddIndex(
            model_name='taskcategorymodel',
            index=models.Index(fields=['owner_user'], include=('id', 'name', 'color', 'updated_at'), name='idx_task_cat_owner_user'),
        ),
        migrations.AddConstraint(
            model_name='taskcategorymodel',
            constraint=models.UniqueConstraint(fields=('owner_user', 'name'), name='uq_task_categories_owner_name'),
        ),
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['owner_user', '-created_at'], include=('id', 'title', 'is_completed', 'category', 'updated_at'), name='idx_tasks_owner_created'),
        ),
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['owner_user', 'is_completed', '-created_at'], include=('id', 'title', 'category', 'updated_at'), name='idx_tasks_owner_done_created'),
        ),
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['owner_user', 'category', '-created_at'], include=('id', 'title', 'is_completed', 'updated_at'), name='idx_tasks_owner_cat_created'),
        ),
        migrations.AddIndex(
            model_name='tasksharemodel',
            index=models.Index(fields=['task'], include=('shared_with_user', 'permission', 'created_at'), name='idx_task_shares_task'),
        ),
        migrations.AddIndex(
            model_name='tasksharemodel',
            index=models.Index(fields=['shared_with_user', '-created_at'], include=('task', 'permission'), name='idx_shares_shared_user_created'),
        ),
        migrations.AddConstraint(
            model_name='tasksharemodel',
            constraint=models.UniqueConstraint(fields=('task', 'shared_with_user'), name='uq_task_shares_task_user'),
        ),
        migrations.AddConstraint(
            model_name='tasksharemodel',
            constraint=models.CheckConstraint(condition=models.Q(('permission__in', ['reader'])), name='chk_task_shares_permission'),
        ),
    ]
