# Generated by Django 6.0.8 on 2026-08-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_share_reader_permission"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taskcategorymodel",
            name="idx_task_cat_owner_user",
        ),
    ]
