# Generated by Django 6.0.8 on 2026-08-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_redundant_category_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tasksharemodel",
            name="idx_task_shares_task",
        ),
    ]
